In [3]:
import numpy as np

### Operations on Numpy array

In [4]:
numpy_arr=np.array([2,3,4,5,6,7,8,9])
print("our numpy array is : \n",numpy_arr)
print("slicing operations numpy_arr[0:1]: ",numpy_arr[0:1])
print("slicing operations numpy_arr[0:8]: ",numpy_arr[0:8])
print("slicing operations numpy_arr[3:8:2]: ",numpy_arr[3:8:2])
print("slicing operations numpy_arr[2::3]: ",numpy_arr[2::3])
print("slicing operations numpy_arr[8::-1]: ",numpy_arr[8::-1])


our numpy array is : 
 [2 3 4 5 6 7 8 9]
slicing operations numpy_arr[0:1]:  [2]
slicing operations numpy_arr[0:8]:  [2 3 4 5 6 7 8 9]
slicing operations numpy_arr[3:8:2]:  [5 7 9]
slicing operations numpy_arr[2::3]:  [4 7]
slicing operations numpy_arr[8::-1]:  [9 8 7 6 5 4 3 2]


In [5]:
arr2d=np.array([[5,6,7],[3,0,8],[2,1,4]])
print("slicing in 2D array ---> matrix ",arr2d[2,1])   # gives elent at row 2 and col 1
print("complete row : ",arr2d[1])                      # gives complete row
print("complete col : ",arr2d[:,1])                    # gives complete col

slicing in 2D array ---> matrix  1
complete row :  [3 0 8]
complete col :  [6 0 1]


### Sorting in 1D & 2D

In [6]:
unsorted=np.array([6,9,4,1,0,5,1,4,7,3,8])
print("sorted array : ",np.sort(unsorted))

array_2d=np.array([[5,1],[7,5],[1,7]])
print("sorted 2D array : \n",np.sort(array_2d,axis=0))   # sort entire 2d matrix
print("sorted 2D array : \n",np.sort(array_2d,axis=1))   # sort each row individually

sorted array :  [0 1 1 3 4 4 5 6 7 8 9]
sorted 2D array : 
 [[1 1]
 [5 5]
 [7 7]]
sorted 2D array : 
 [[1 5]
 [5 7]
 [1 7]]


### Filter

In [7]:
num=np.array([6,7,3,4,0,2,5])
even=num[num%2==0]
print("array even is : ",even)

odd=num[num%2==1]
print("array odd is : ",odd)

array even is :  [6 4 0 2]
array odd is :  [7 3 5]


### Filter with mask

In [11]:
# above written statement for evaluating odd or even no. inside [] is mask
mask1=num>=5
print("numbers that are greater than or equal to 5 in num are: ",num[mask1])

mask2=num!=2
print("numbers that are not equal to 2 in num are: ",num[mask2])


numbers that are greater than or equal to 5 in num are:  [6 7 5]
numbers that are not equal to 2 in num are:  [6 7 3 4 0 5]


In [13]:
# np.where()
where=np.where(num<4)
print("index where written condition is true : ",where)
print("elements in num for which condition is true : ",num[where])

index where written condition is true :  (array([2, 4, 5]),)
elements in num for which condition is true :  [3 0 2]


In [19]:
wh1=np.where(num%2==0,"true","false")
print(num)
print(wh1)


# best example to understand np.where() is above written statement, it work like :-
"""

if(num%2==0){
    'true'
}
else{
    'false'
}

"""

[6 7 3 4 0 2 5]
['true' 'false' 'false' 'true' 'true' 'true' 'false']


"\n\nif(num%2==0){\n    'true'\n}\nelse{\n    'false'\n}\n\n"

### Adding and Removing data

In [21]:
ar1=np.array([2,3,4])
ar2=np.array([1,4,2])
combined=ar1+ar2
print("combined array is : ",combined)

# result:-
# 2+1=3
# 3+4=7
# 4+2=6

# simply adding ar1 and ar2 will add up elements at same index not concatenating for avoiding this problem:-

concat=np.concatenate((ar1,ar2))
print("array 1 and 2 after using np.concatenate() :- ",concat)

combined array is :  [3 7 6]
array 1 and 2 after using np.concatenate() :-  [2 3 4 1 4 2]


In [23]:
# compatibility of different data is very important to operate on them so we check it by :-

a=np.array([1,2,3])
b=np.array([3,4,5])
c=np.array([7,8,9,0])

print("a and b are compatible? ",a.shape==b.shape)
print("a and c are compatible? ", a.shape==c.shape)

a and b are compatible?  True
a and c are compatible?  False


In [28]:
matrix=np.array([[3,4],[1,6]])

add_row=np.array([2,3])
final_mat=np.vstack((matrix,add_row))                 # size will be increased in vertical dir. ---> row addition
print("matrix after row addition : \n",final_mat)

add_col=np.array([[1],[5]])
final_mat=np.hstack((matrix,add_col))                 # size will be increased in horizontal dir. ---> col addition
print("matrix after column addition : \n",final_mat)

matrix after row addition : 
 [[3 4]
 [1 6]
 [2 3]]
matrix after column addition : 
 [[3 4 1]
 [1 6 5]]


In [39]:
dummy=np.array([3,4,5,6,1,0])
after_del=np.delete(dummy,4)         # index that you want to delete
print("dummy array after deletion of index 4 : ",after_del)

after_del=np.delete(dummy,(3,5))
print("dummy array after deletion of index 3 and 5 : ",after_del)

dummy array after deletion of index 4 :  [3 4 5 6 0]
dummy array after deletion of index 3 and 5 :  [3 4 5 1]
