## Numpy basics - Array and matrices


In [ ]:
import time
import numpy as np

In [ ]:
array1=np.array([2,3,7,9,4])            #1-D array
print("array_1 is : \n",array1)

array2=np.array([[2,3,4],               #2-D array ---> matrices
                 [4,5,6]])
print("array2 is : \n",array2)

array_1 is : 
 [2 3 7 9 4]
array2 is : 
 [[2 3 4]
 [4 5 6]]


### LIST v/s Numpy Array


In [ ]:
my_lst=[1,2,3]
print("my_list is ",my_lst*2,"after * with 2(scalar)")    #append same list at the end  

num_arr=np.array([1,2,3])
print("numpy array is",num_arr*2,"after * with 2(scalar)")   #change each element with *2 of element

my_list is  [1, 2, 3, 1, 2, 3] after * with 2(scalar)
numpy array is [2 4 6] after * with 2(scalar)


### understanding time required in list and array

In [9]:
start=time.time()
py_list=[i*3 for i in range(1000000)]                                       # takes more time
print("time taken for this operation is: ",time.time()-start)


start=time.time()
numpy_lst=np.arange(1000000)*2                                              # takes much lesser time
print("time taken fro this operation is: ",time.time()-start)

time taken for this operation is:  0.16469264030456543
time taken fro this operation is:  0.009261846542358398


### Arrays :-

In [24]:
zeros=np.zeros((2,3))
print("this will create a matix of 4*3 with all elements 0 \n",zeros)
print("\n")

ones=np.ones([2,2])
print("this will create a matrix of size 2*2 with all elements 1\n",ones)
print("\n")

full=np.full((3,2),4)
print("full shows the size of matrix and the element values\n",full)
print("\n")

random=np.random.random((3,2))
print("random value in matrix of size 2*3 with values b/w 0 and 1\n",random)

this will create a matix of 4*3 with all elements 0 
 [[0. 0. 0.]
 [0. 0. 0.]]


this will create a matrix of size 2*2 with all elements 1
 [[1. 1.]
 [1. 1.]]


full shows the size of matrix and the element values
 [[4 4]
 [4 4]
 [4 4]]


random value in matrix of size 2*3 with values b/w 0 and 1
 [[0.39004479 0.99730614]
 [0.51708833 0.90770412]
 [0.87162924 0.21877106]]


In [31]:
# start, stop, step ----> in this start is included in range but stop is not included
# for stop = 5 ---> we will only go upto 4

sequence=np.arange(1,10,1)
print("sequence with (1,10,1) is : ",sequence)

sequence=np.arange(10,20,2)
print("sequence with (10,20,2) is : ",sequence)

sequence=np.arange(0,51,5)
print("sequence with (0,51,5) is : ",sequence)


sequence with (1,10,1) is :  [1 2 3 4 5 6 7 8 9]
sequence with (10,20,2) is :  [10 12 14 16 18]
sequence with (0,51,5) is :  [ 0  5 10 15 20 25 30 35 40 45 50]


### vector , matrix , tensor

In [32]:
vector=np.array([4,5,6,7])
print("vector is : \n",vector)
print("\n")

matrix=np.array([[4,5,6,7],[1,2,5,0]])
print("matrix is : \n",matrix)
print("\n")

tensor=np.array([[[2,3],[4,5]],[[1,0],[6,7]]])
print("tensor is : \n",tensor)
print("\n")

vector is : 
 [4 5 6 7]


matrix is : 
 [[4 5 6 7]
 [1 2 5 0]]


tensor is : 
 [[[2 3]
  [4 5]]

 [[1 0]
  [6 7]]]




### Array properties

In [ ]:
arr1=np.array([[2,3,4],[6,8,7]])
print("arr1 is: \n",arr1)
print("size : ",arr1.size)                  # no. of elements
print("dimention : ",arr1.ndim)
print("shape : ",arr1.shape)
print("data type : ",arr1.dtype)

arr1 is: 
 [[2 3 4]
 [6 8 7]]
size :  6
dimention :  2
shape :  (2, 3)
data type :  int64


In [43]:
arr2=np.arange(12)
print("arr2 is : \n",arr2)

reshape=arr2.reshape((4,3))
print("reshaped array :\n",reshape)

flatten=reshape.flatten()
print("flatten array is : \n",flatten)

transpose=reshape.T
print("tanspose of reshaped array is : \n",transpose)

arr2 is : 
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
reshaped array :
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
flatten array is : 
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
tanspose of reshaped array is : 
 [[ 0  3  6  9]
 [ 1  4  7 10]
 [ 2  5  8 11]]
